name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build -t my-app-image .
        docker tag my-app-image:latest myregistry.azurecr.io/my-app-image:latest
        echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login myregistry.azurecr.io --username ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

    - name: Set up Azure CLI
      uses: azure/CLI@v1

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-name'  # Replace with your Azure app name
        slot-name: 'staging'       # Replace with your desired slot name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

